# .travis.yml for travis-ci.org
#
# Test configuration:
# - cli          : travis lint ./.travis.yml

dist: trusty

git:
  depth: 3
  quiet: true

branches:
  only:
    - master

language: scala

scala:
  - 2.11.12

jdk:
  - oraclejdk8

script:
  - gradle wrapper
  - nvm install
  - npm install @angular/cli@6.0.0
  - ./script/test_ng.sh

#script:
#  - ./gradlew check --full-stacktrace

#after_success:
#  - ./gradlew test jacocoTestReport
