# .travis.yml for travis-ci.org
#
# Test configuration:
# - cli          : travis lint ./.travis.yml

dist: trusty
sudo: required

git:
  depth: 3
  quiet: true

language: scala
scala:
  - 2.11.12

jdk:
  - oraclejdk8

branches:
  only:
    - master

install:
  - gradle wrapper
  - nvm install

after_success:
  - ./gradlew test jacocoTestReport
