# .travis.yml for travis-ci.org
#
# Test configuration:
# - cli          : travis lint ./.travis.yml

branches:
  only:
    - master

dist: trusty
sudo: required

git:
  depth: 3
  quiet: true

install: true

language: scala

scala:
  - 2.11.12

jdk:
  - oraclejdk8

node_js:
  - node

before_script:
  - gradle wrapper
  - nvm install

after_success:
  - ./gradlew test jacocoTestReport
